name: NFL, update & export

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  schedule:
    # Thursdays 11:28pm, Sundays 7:58pm & 11:28pm, account for UTC conversion
    - cron: "58 0 * 9-12,1 1" # Sunday 7:58pm EST  →  00:58 UTC Monday  (day-of-week = Monday)
    - cron: "15 1 * 9-12,1 1" # Sunday 8:15pm EST  →  01:15 UTC Monday  (day-of-week = Monday)
    - cron: "28 4 * 9-12,1 1" # Sunday 11:28pm EST → 04:28 UTC Monday (day-of-week = Monday)
    - cron: "28 4 * 9-12,1 5" # Thursday 11:28pm EST → 04:28 UTC Friday (day-of-week = Friday)
  workflow_dispatch: # Allows manual triggering

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    env:
      TZ: America/New_York

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install \
            pandas \
            python-dotenv \
            requests \
            pillow \
            numpy \
            scipy \
            espn-api

      - name: Push median script
        run: |
          python backend/median-np.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated median update"
          git push
        continue-on-error: true # Prevent failure if no changes
